remote_theme: pmarsceill/just-the-docs
color_scheme: darkgarden
search_enabled: false
title: Gardening Chat
footer_content: "Grow things. Have fun."
aux_links:
  "Chat now":
    - "https://kiwiirc.com/client/chat.freenode.net/##gardening"
  "This site on github":
    - "https://github.com/gardening-chat/gardening-chat.github.io"
